[package]
name = "lsystem-macro"
version = "0.1.0"
authors = ["eric556 <enpie123@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1", features = ["full"] }